services:
  uj-admin-panel:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: uj_wifi_backend
    ports:
      - "5001:5001"
    restart: always

  uj-portal:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: uj_wifi_frontend
    ports:
      - "3000:80"
    restart: always